// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnxctwrxpimklbdldhoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_S8O5YmFcrWtrJ2FLyLYqag_bJk-QQcT";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
